version: '3.7'

services:
  web:
    build: ./
      # context: ./
      # dockerfile: ./D
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lottee:/usr/src/lottee/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lottee
    ports:
      - 5432
volumes:
  postgres_data:
