version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URI=http://backend/api
    volumes:
      - ./frontend:/lottee/frontend
    depends_on:
      - backend    # <-- will become useless if change API_URI=
    networks:
      - main

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lottee
    ports:
      - "8000:8000"
    networks:
      - main

networks:
  main:
