version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URI=http://backend/api
    volumes:
      - ./frontend:/lottee/frontend
    depends_on:
      - backend    # <-- will become useless if change API_URI=
    networks:
      - main

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/lottee
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - main

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    container_name: redis
    networks:
      - main

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/postgresql/data
    env_file: .env
    restart: always
    networks:
      - main
volumes:
  postgres_data:
