# Generated by Django 3.1.1 on 2020-09-27 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='owner',
            new_name='user',
        ),
    ]
