# Generated by Django 3.1.2 on 2020-11-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0003_auto_20200927_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Score for prize'),
        ),
    ]
