# Generated by Django 3.1.2 on 2020-11-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0004_number_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='score',
        ),
    ]
