# Generated by Django 3.1.2 on 2020-12-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Youtube', max_length=32)),
                ('link', models.URLField()),
                ('icon', models.CharField(default='cloud', max_length=32)),
                ('color', models.CharField(default='#ffffff', max_length=16)),
                ('subscribe', models.BooleanField(default=False)),
                ('like', models.BooleanField(default=False)),
                ('repost', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='lot/')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='Название')),
                ('description', models.CharField(max_length=160, null=True, verbose_name='Описание')),
                ('players', models.PositiveSmallIntegerField(default=3, verbose_name='Кол-во участников')),
                ('winners', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во победилей')),
                ('energy', models.PositiveSmallIntegerField(default=1, verbose_name='Затрата энергии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменений')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активность игры')),
            ],
        ),
    ]
