# Generated by Django 3.1.2 on 2020-11-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0004_lotimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='image',
        ),
    ]
